import * as v from "valibot";

export const SessionResponseSchema = v.object({
    payment_session_id: v.pipe(
        v.string(),
        v.regex(/^[a-zA-Z0-9-]{27}$/),
        v.description("A unique identifier for the Payment Session."),
    ),
    created: v.pipe(v.string(), v.description("ISO 8601 date-time format when the session was created.")),
    updated: v.pipe(v.string(), v.description("ISO 8601 date-time format when the session was last updated.")),
    reference_id: v.pipe(
        v.string(),
        v.minLength(1),
        v.maxLength(64),
        v.description(
            "Your reference to uniquely identify the Payment Session. This is commonly used to identify your order or transaction.",
        ),
    ),
    customer_id: v.pipe(
        v.string(),
        v.regex(/^[a-zA-Z0-9-]{41}$/),
        v.description(
            "A unique identifier automatically generated by Xendit to represent an end customer. This ID can be used as a consistent reference across multiple transactions or payment activities for the same user.",
        ),
    ),
    session_type: v.pipe(
        v.picklist(["SAVE", "PAY"]),
        v.description(
            "The use case for Payment Session. SAVE: save the payment details for future payments. PAY: collects a one-time payment from a customer.",
        ),
    ),
    allow_save_payment_method: v.pipe(
        v.picklist(["DISABLED", "OPTIONAL", "FORCED"]),
        v.description(
            "Option to save payment details from a customer for the PAY session_type. DISABLED: does not save the payment details. OPTIONAL: allows the customer to opt-in to save the payment details. FORCED: always save the payment details.",
        ),
    ),
    currency: v.pipe(
        v.picklist(["IDR", "PHP", "VND", "THB", "SGD", "MYR", "USD"]),
        v.description("ISO 4217 three-letter currency code for the payment."),
    ),
    amount: v.pipe(
        v.number(),
        v.minValue(0),
        v.description("The payment amount to be collected from the customer. For SAVE session_type, amount must be 0."),
    ),
    country: v.pipe(
        v.picklist(["ID", "PHP", "VND", "TH", "SG", "MY"]),
        v.description("ISO 3166-1 alpha-2 two-letter country code for the payment."),
    ),
    mode: v.pipe(
        v.picklist(["PAYMENT_LINK", "COMPONENTS"]),
        v.description(
            "The frontend integration mode for Payment Session. PAYMENT_LINK: redirect customer to the Xendit Hosted Checkout page. COMPONENTS: collect payment details from customer with Xendit Component SDK.",
        ),
    ),
    capture_method: v.pipe(
        v.picklist(["AUTOMATIC", "MANUAL"]),
        v.description(
            "The method to capture the payment. AUTOMATIC: capture the payment automatically. MANUAL: capture the payment manually using Payment Capture API.",
        ),
    ),
    channel_properties: v.pipe(
        v.object({}),
        v.description("Optional channel specific properties to be sent to specific payment channel provider."),
    ),
    allowed_payment_channels: v.array(v.string()),
    expires_at: v.pipe(
        v.string(),
        v.description(
            "ISO 8601 date-time format. By default the Session will expire 30 minutes after creation. We recommend you to keep Sessions short-lived and create a new Session again only when the customer is ready to make payment.",
        ),
    ),
    locale: v.pipe(v.string(), v.description("ISO 639-1 two-letter language code for Hosted Checkout page.")),
    metadata: v.pipe(
        v.object({}),
        v.description(
            "Key-value entries for your custom data/information. You can specify up to 50 keys, with key names up to 40 characters and values up to 500 characters. This is commonly used for your internal reconciliation purposes. Xendit will not use this data for any processing.",
        ),
    ),
    items: v.nullable(v.array(v.object({}))),
    success_return_url: v.pipe(
        v.string(),
        v.description(
            "Specify the URL to redirect the customer after the session is completed or expired, or if the customer decide to stop the payment process. Must be HTTPS.",
        ),
    ),
    cancel_return_url: v.pipe(
        v.string(),
        v.description(
            "Specify the URL to redirect the customer after the session is completed or expired, or if the customer decide to stop the payment process. Must be HTTPS.",
        ),
    ),
    status: v.pipe(
        v.picklist(["ACTIVE", "COMPLETED", "EXPIRED", "CANCELED"]),
        v.description("The status of the Payment Session."),
    ),
    payment_link_url: v.nullable(
        v.pipe(
            v.string(),
            v.description(
                "The URL for Xendit Hosted Checkout page. Redirect your customer to this URL to complete the payment.",
            ),
        ),
    ),
    payment_token_id: v.nullable(
        v.pipe(
            v.string(),
            v.description("Xendit Payment Token ID used to reference the saved payment details from the customer."),
        ),
    ),
    payment_id: v.nullable(
        v.pipe(
            v.string(),
            v.description("Xendit Payment ID used to reference the charged payment details from the customer."),
        ),
    ),
    payment_request_id: v.nullable(
        v.pipe(
            v.string(),
            v.description("Xendit Payment Request ID used to reference the payment made during this Session."),
        ),
    ),
    business_id: v.nullable(v.pipe(v.string(), v.description("Business ID associated with the session."))),
});
