import * as z from 'zod';

const SessionResponseSchema = z
  .object({
    payment_session_id: z
      .string()
      .regex(/^[a-zA-Z0-9-]{27}$/)
      .meta({ description: 'A unique identifier for the Payment Session.' }),
    created: z.string().meta({ description: 'ISO 8601 date-time format when the session was created.' }),
    updated: z.string().meta({ description: 'ISO 8601 date-time format when the session was last updated.' }),
    reference_id: z
      .string()
      .min(1)
      .max(64)
      .meta({ description: 'Your reference to uniquely identify the Payment Session.' }),
    customer_id: z
      .string()
      .regex(/^[a-zA-Z0-9-]{41}$/)
      .meta({ description: 'A unique identifier automatically generated by Xendit to represent an end customer.' }),
    session_type: z.enum(['SAVE', 'PAY']).meta({ description: 'The use case for Payment Session.' }),
    allow_save_payment_method: z
      .enum(['DISABLED', 'OPTIONAL', 'FORCED'])
      .meta({ description: 'Option to save payment details from a customer for the PAY session_type.' }),
    currency: z
      .enum(['IDR', 'PHP', 'VND', 'THB', 'SGD', 'MYR', 'USD'])
      .meta({ description: 'ISO 4217 three-letter currency code for the payment.' }),
    amount: z.number().min(0).meta({ description: 'The payment amount to be collected from the customer.' }),
    country: z
      .enum(['ID', 'PHP', 'VND', 'TH', 'SG', 'MY'])
      .meta({ description: 'ISO 3166-1 alpha-2 two-letter country code for the payment.' }),
    mode: z
      .enum(['PAYMENT_LINK', 'COMPONENTS'])
      .meta({ description: 'The frontend integration mode for Payment Session.' }),
    capture_method: z
      .enum(['AUTOMATIC', 'MANUAL'])
      .optional()
      .meta({ description: 'The method to capture the payment.' }),
    channel_properties: z
      .object({})
      .optional()
      .meta({ description: 'Optional channel specific properties to be sent to specific payment channel provider.' }),
    allowed_payment_channels: z.array(z.string()).optional(),
    expires_at: z.string().optional().meta({ description: 'ISO 8601 date-time format.' }),
    locale: z.string().meta({ description: 'ISO 639-1 two-letter language code for Hosted Checkout page.' }),
    metadata: z
      .record(z.string(), z.any())
      .meta({ description: 'Key-value entries for your custom data/information.' }),
    items: z.array(z.object({})).nullable().optional(),
    success_return_url: z
      .string()
      .optional()
      .meta({ description: 'Specify the URL to redirect the customer after the session is completed or expired.' }),
    cancel_return_url: z
      .string()
      .optional()
      .meta({ description: 'Specify the URL to redirect the customer after the session is completed or expired.' }),
    status: z
      .enum(['ACTIVE', 'COMPLETED', 'EXPIRED', 'CANCELED'])
      .meta({ description: 'The status of the Payment Session.' }),
    payment_link_url: z
      .string()
      .nullable()
      .optional()
      .meta({ description: 'The URL for Xendit Hosted Checkout page.' }),
    payment_token_id: z
      .string()
      .nullable()
      .optional()
      .meta({ description: 'Xendit Payment Token ID used to reference the saved payment details from the customer.' }),
    payment_id: z
      .string()
      .nullable()
      .optional()
      .meta({ description: 'Xendit Payment ID used to reference the charged payment details from the customer.' }),
    payment_request_id: z
      .string()
      .nullable()
      .optional()
      .meta({ description: 'Xendit Payment Request ID used to reference the payment made during this Session.' }),
    business_id: z.string().nullable().optional().meta({ description: 'Business ID associated with the session.' }),
  })
  .meta({ description: 'Session response schema', example: [{ payment_session_id: 'ps-...', amount: 100 }] });

export const GetSessionStatusResponseSchema = SessionResponseSchema;
export const CancelSessionResponseSchema = SessionResponseSchema;
export const CreateSessionResponseSchema = SessionResponseSchema;
