import * as z from 'zod';
import { MetadataSchema, PhoneNumberSchema } from '@standard/schema';

import { BusinessDetailSchema } from './business_detail';
import { IdentityAccountSchema } from './identity_account';
import { IndividualDetailSchema } from './individual_detail';
import { KycDocumentsObjectSchema } from './kyc_document';
import { StandardAddressSchema } from './address';

export const DescriptionSchema = z
  .string()
  .regex(/^[a-zA-Z0-9]{2,500}$/)
  .nullable()
  .optional()
  .meta({
    description:
      'Merchant-provided description for the customer. Characters alphanumeric. No special characters is allowed.',
  });

export const DateofRegistrationSchema = z
  .string()
  .nullable()
  .optional()
  .meta({ description: "Date of which the account that the shopper had to create/sign up on the merchant's website" });

export const CustomerIdFieldSchema = z
  .string()
  .regex(/^[a-zA-Z0-9-]{41}$/)
  .meta({
    description:
      'A unique identifier automatically generated by Xendit to represent an end customer. Example: cust-b98d6f63-d240-44ec-9bd5-aa42954c4f48',
  });

export const CustomerSchema = z
  .object({
    id: CustomerIdFieldSchema,
    reference_id: z.string().min(1).max(255).optional(),
    type: z.enum(['INDIVIDUAL', 'BUSINESS']),
    mobile_number: PhoneNumberSchema.optional(),
    phone_number: PhoneNumberSchema.optional(),
    individual_detail: IndividualDetailSchema.nullable()
      .optional()
      .meta({ description: 'Required if type is INDIVIDUAL' }),
    business_detail: BusinessDetailSchema.nullable().optional().meta({ description: 'Required if type is BUSINESS' }),
    identity_accounts: z.array(IdentityAccountSchema).optional(),
    kyc_documents: z.array(KycDocumentsObjectSchema).optional(),
    addresses: z.array(StandardAddressSchema).optional(),
    hashed_phone_number: z.string().min(1).max(255).nullable().optional(),
    created: z.string().meta({ description: 'Customer creation timestamp' }),
    updated: z.string().meta({ description: 'Customer last update timestamp' }),
    metadata: MetadataSchema.optional(),
    date_of_registration: DateofRegistrationSchema,
    description: DescriptionSchema,
  })
  .meta({ description: 'Customer object', example: { id: 'cust-xxxx', type: 'INDIVIDUAL' } });
