import * as v from "valibot";
import { MetadataSchema } from "@standard/schema";
import { PhoneNumberSchema } from "@standard/schema";

import { BusinessDetailSchema } from "./business_detail";
import { IdentityAccountSchema } from "./identity_account";
import { IndividualDetailSchema } from "./individual_detail";
import { KycDocumentsObjectSchema } from "./kyc_document";
import { StandardAddressSchema } from "./address";

export const DescriptionSchema = v.nullable(
    v.pipe(
        v.string(),
        v.regex(/^[a-zA-Z0-9]{2,500}$/),
        v.description(
            "Merchant-provided description for the customer. Characters alphanumeric. No special characters is allowed.",
        ),
    ),
);

export const DateofRegistrationSchema = v.nullable(
    v.pipe(
        v.string(),
        v.description("Date of which the account that the shopper had to create/sign up on the merchant's website"),
    ),
);

export const CustomerIdFieldSchema = v.pipe(
    v.string(),
    v.regex(/^[a-zA-Z0-9-]{41}$/),
    v.description(
        "A unique identifier automatically generated by Xendit to represent an end customer. This ID can be used as a consistent reference across multiple transactions or payment activities for the same user. Example: cust-b98d6f63-d240-44ec-9bd5-aa42954c4f48",
    ),
);

export const CustomerSchema = v.object({
    id: CustomerIdFieldSchema,
    reference_id: v.pipe(v.string(), v.minLength(1), v.maxLength(255)),
    type: v.picklist(["INDIVIDUAL", "BUSINESS"]),
    mobile_number: PhoneNumberSchema,
    phone_number: PhoneNumberSchema,
    individual_detail: v.nullable(v.pipe(IndividualDetailSchema, v.description("Required if type is INDIVIDUAL"))),
    business_detail: v.nullable(v.pipe(BusinessDetailSchema, v.description("Required if type is BUSINESS"))),
    identity_accounts: v.array(IdentityAccountSchema),
    kyc_documents: v.array(KycDocumentsObjectSchema),
    addresses: v.array(StandardAddressSchema),
    hashed_phone_number: v.nullable(v.pipe(v.string(), v.minLength(1), v.maxLength(255))),
    created: v.pipe(v.string(), v.description("Customer creation timestamp")),
    updated: v.pipe(v.string(), v.description("Customer last update timestamp")),
    metadata: MetadataSchema,
    date_of_registration: DateofRegistrationSchema,
    description: DescriptionSchema,
});
