import { radius, spacing, ThemeColors } from '@repo/theme';
import { StyleSheet } from 'react-native';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    heroCard: {
      backgroundColor: colors.home.heroStart,
      borderRadius: radius.xxl,
      borderWidth: 1,
      borderColor: colors.home.heroAccent,
      padding: spacing.heroInset,
      overflow: 'hidden',
    },
    profileRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: spacing.s,
    },
    profileLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    profileCopy: {
      marginLeft: spacing.s,
      flex: 1,
      minWidth: 0,
    },
    heroBrowsePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      borderRadius: radius.round,
      backgroundColor: colors.home.chipBg,
      paddingHorizontal: spacing.s,
      paddingVertical: spacing.xs,
      borderWidth: 1,
      borderColor: colors.home.heroAccent,
    },
    heroTitle: {
      marginTop: spacing.m,
      marginBottom: spacing.s,
    },
    heroBadgeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.s,
      flexWrap: 'wrap',
    },
    heroBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
      borderRadius: radius.round,
      backgroundColor: colors.home.chipBg,
      paddingHorizontal: spacing.s,
      paddingVertical: spacing.xs,
    },
    searchContainer: {
      paddingHorizontal: spacing.pageHorizontal,
      paddingVertical: spacing.m,
    },
    searchBar: {
      borderRadius: radius.l,
      borderWidth: 1,
      borderColor: colors.card.stroke,
      backgroundColor: colors.card.base,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 8,
    },
    searchResults: {
      position: 'absolute',
      top: 62,
      left: spacing.pageHorizontal,
      right: spacing.pageHorizontal,
      backgroundColor: colors.card.base,
      borderRadius: radius.l,
      borderWidth: 1,
      borderColor: colors.card.stroke,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.16,
      shadowRadius: 20,
      elevation: 8,
      maxHeight: 320,
      zIndex: 100,
    },
    searchLoading: {
      padding: spacing.m,
      alignItems: 'center',
    },
    searchEmpty: {
      paddingVertical: spacing.s,
    },
    searchResultItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.s,
      paddingHorizontal: spacing.m,
      paddingVertical: spacing.s,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    searchResultContent: {
      flex: 1,
      minWidth: 0,
    },
    searchResultMeta: {
      alignItems: 'flex-end',
      gap: spacing.xxs,
    },
    searchPrice: {
      fontWeight: '600',
    },
    scrollArea: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: spacing.pageHorizontal,
      paddingBottom: spacing.xxxl,
      gap: spacing.s,
    },
    sectionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: spacing.s,
      marginTop: spacing.s,
    },
    sectionAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xxs,
      paddingHorizontal: spacing.xs,
      paddingVertical: spacing.xxs,
    },
    quickActionGrid: {
      flexDirection: 'row',
      gap: spacing.gridGap,
      marginBottom: spacing.m,
    },
    quickActionCardPrimary: {
      flex: 1,
      backgroundColor: colors.home.heroStart,
      borderColor: colors.home.heroAccent,
      borderWidth: 1,
      borderRadius: radius.l,
      padding: spacing.cardInset,
      minHeight: 146,
      justifyContent: 'space-between',
    },
    quickActionCardSecondary: {
      flex: 1,
      backgroundColor: colors.card.muted,
      borderColor: colors.card.stroke,
      borderWidth: 1,
      borderRadius: radius.l,
      padding: spacing.cardInset,
      minHeight: 146,
      justifyContent: 'space-between',
    },
    quickActionTitle: {
      marginTop: spacing.xs,
      marginBottom: spacing.s,
    },
    quickActionFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    serviceGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: spacing.gridGap,
      marginBottom: spacing.s,
    },
    serviceTypeTile: {
      width: '48.5%',
      backgroundColor: colors.card.base,
      borderRadius: radius.l,
      borderWidth: 1,
      borderColor: colors.card.stroke,
      paddingVertical: spacing.m,
      paddingHorizontal: spacing.s,
      alignItems: 'center',
      minHeight: 124,
      justifyContent: 'center',
      gap: spacing.s,
    },
    serviceTypeIconShell: {
      width: 58,
      height: 58,
      borderRadius: 20,
      backgroundColor: colors.home.chipBg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.home.heroAccent,
    },
    serviceTypeFallback: {
      width: 24,
      height: 24,
      borderRadius: 8,
      backgroundColor: colors.border,
    },
    featuredList: {
      width: '100%',
      paddingTop: spacing.xs,
      paddingRight: 0,
      gap: spacing.s,
    },
    featuredCard: {
      width: '100%',
      borderRadius: radius.l,
      borderWidth: 1,
      borderColor: colors.card.stroke,
      backgroundColor: colors.card.base,
      padding: spacing.m,
      justifyContent: 'space-between',
      minHeight: 152,
    },
    featuredTitle: {
      marginTop: spacing.xxs,
    },
    featuredProviderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: spacing.s,
      marginBottom: spacing.s,
      gap: spacing.xs,
    },
    featuredProviderName: {
      flex: 1,
      minWidth: 0,
    },
    featuredMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.s,
    },
    inlineEmptyState: {
      borderRadius: radius.l,
      borderWidth: 1,
      borderColor: colors.card.stroke,
      backgroundColor: colors.card.muted,
      paddingVertical: spacing.s,
    },
  });
